Fix NoClassDefFoundError with Gradle 4.3 or earlier (again).
This bug was fixed in commit 4e869f86986c4384f4df4f2d2007cf111275d038,
but reappeared after commit f5be403f9470d1b5d69a5b0f3b53225102b3487d:
AppPlugin references the new ModelBuilder, making build or sync fail
on older Gradle versions before the plugin can run a version check to
provide a message asking users to update their Gradle version.

This fix slightly decreases code design, but hopefully it's still
acceptable.

Fixes: 73383831
Test: New GradleVersionCheckTest
Change-Id: Ic625489c6121921a6a850f546afaa217a8afc1a0