Fix aapt proto jar override of aia proto jar
Change 03e493b introduced a bug in production builds where
aia_manifest_proto_1.0_jarjar library, which pointed to a jarjar.jar
file was overriden by another generated jarjar.jar (same name) pointed
by aapt-proto-jarjar.

This bug does not exist in dev builds, since libraries in this case
are located in bazel-generated folder in different locations, but in
production builds they live all under android-studio/lib and were
conflicting due to the same name.

This CL renames the artifacts correctly, which make exported jars
correct and avoids NoClassDefFoundError.

Test: ./build_studio.sh and follow steps in bug
Change-Id: I84e6237afe793e4c3655b7d13d6badc120116461
Fixes: 78212467